REPORT:report## report.mk
report:## report	environment ARGS
	@echo ''
	@echo ' TIME=${TIME}	'
	@echo ' CURRENT_PATH=${CURRENT_PATH}	'
	@echo ' THIS_DIR=${THIS_DIR}	'
	@echo ' PROJECT_NAME=${PROJECT_NAME}	'
	@echo ''
	@echo ' NODE_VERSION=${NODE_VERSION}	'
	@echo ' NODE_ALIAS=${NODE_ALIAS}	'
	@echo ' EMSDK=${EMSDK}	'
	@echo ' EMSDK_NODE=${EMSDK_NODE}	'
	@echo ' EMSDK_PYTHON=${EMSDK_PYTHON}	'
	@echo ' EMCC=${EMCC}	'
	@echo ''
	@echo ' POWERSHELL=${POWERSHELL}	'
	@echo ''
	@echo ' PACKAGE_MANAGER=${PACKAGE_MANAGER}	'
	@echo ' PACKAGE_INSTALL=${PACKAGE_INSTALL}	'
	@echo ''
	@echo ' PYTHON=${PYTHON}'
	@echo ' PYTHON2=${PYTHON2}'
	@echo ' PYTHON3=${PYTHON3}'
	@echo ''
	@echo ' NODE_GYP_FORCE_PYTHON=${NODE_GYP_FORCE_PYTHON}'
	@echo ' PYTHON_VERSION=${PYTHON_VERSION}'
	@echo ' PYTHON_VERSION_MAJOR=${PYTHON_VERSION_MAJOR}'
	@echo ' PYTHON_VERSION_MINOR=${PYTHON_VERSION_MINOR}'
	@echo ' PIP=${PIP}'
	@echo ' PIP2=${PIP2}'
	@echo ' PIP3=${PIP3}'
	@echo ''
	@echo ' GIT_USER_NAME=${GIT_USER_NAME}	'
	@echo ' GIT_USER_EMAIL=${GIT_USER_EMAIL}	'
	@echo ' GIT_SERVER=${GIT_SERVER}	'
	@echo ' GIT_PROFILE=${GIT_PROFILE}	'
	@echo ' GIT_BRANCH=${GIT_BRANCH}	'
	@echo ' GIT_HASH=${GIT_HASH}	'
	@echo ' GIT_PREVIOUS_HASH=${GIT_PREVIOUS_HASH}	'
	@echo ' GIT_REPO_ORIGIN=${GIT_REPO_ORIGIN}	'
	@echo ' GIT_REPO_NAME=${GIT_REPO_NAME}	'
	@echo ' GIT_REPO_PATH=${GIT_REPO_PATH}	'